spring:
  application:
    name: ms-fixtures

server:
  port: 8085
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
