spring:
  application:
    name: ms-standings

server:
  port: 8086
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

api-football:
  key: ${API_KEY}
  host-url: https://v3.football.api-sports.io

jwt:
  secret: ${JWT_SECRET}