spring:
  application:
    name: ms-teams

server:
  port: 8083
  max-http-request-header-size: 256KB

api-football:
  key: ${API_KEY}
  host-url: https://v3.football.api-sports.io

jwt:
  secret: ${JWT_SECRET}
